// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtwynvzhfhgyeqhygngv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0d3ludnpoZmhneWVxaHlnbmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MTY2ODQsImV4cCI6MjA1NTE5MjY4NH0.y01u9NZt-NaBSaV_5dO2IdqstrBQTm9mu2wNGc-Pgkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);